site_name: Layer Mask Docs
theme:
  name: material

  palette:

    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Dark mode

    - scheme: slate
      primary: deep blue
      toggle:
        icon: material/weather-sunny
        name: Light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.suggest
    - search.highlight